- name: Manage mongo db instances 
  hosts: mongodb
  collections:
     - community.mongodb
  vars:
          #specific_mongodb_version: "4.4"
    mongodb_version: "4.4"
  roles:
     - role: mongodb_linux
     - role: mongodb_repository
     - role: mongodb_install
     - role: mongodb_mongod
