- name: Manage mongo db instances 
  hosts: mongodb
  collections:
     - community.mongodb
  vars:
          #specific_mongodb_version: "4.4"
    mongodb_version: "4.4"
  roles:
     - role: mongodb_linux
     - role: mongodb_repository
     - role: mongodb_install
     - role: mongodb_mongod
  tasks:
    - name: Install python stuff
      package:
        name: ["python-setuptools", "python3-pip"]

    - name: Install pymongo
      pip:
        name: "{{ 'pymongo==3.12.*' if ansible_python_version[0:3] | float < 3.6 else 'pymongo' }}"


    - name: Initialise replicaset
      community.mongodb.mongodb_replicaset:
        login_host: 192.168.1.34:27017
        replica_set: rs0
        validate: yes
        members:
          - 192.168.1.34:27017
          - 192.168.1.251:27017
          - 192.168.1.144:27017

       #  tasks:
       #  - name: Create a replicaset and use a custom priority for each member
       # community.mongodb.mongodb_replicaset:
       # login_host: 192.168.1.34:27017
       # login_user: admin
       # login_password: admin
       # replica_set: rs0
       # members:
       # - host: 192.168.1.227:27017
       #   priority: 1
       # - host: 192.168.1.251:27017
       #   priority: 0.5
       # - host: 192.168.1.144:27017
       #   priority: 0.5
