- name: Manage mongo db instances 
  hosts: mongodb
  collections:
     - community.mongodb
  vars:
    specific_mongodb_version: "6.0.0"
  roles:
     - role: mongodb_linux
     - role: mongodb_repository
       mongodb_version: "6.0"
     - role: mongodb_install
     - role: mongodb_mongod
