- name: Manage proxmox services
  hosts: proxmox
  become: yes
  collections:
    - community.general.proxmox
  vars:
    - ansible_distribution_release: buster
    - proxmox_release: proxmox-ve-release-6.x.gpg
    - pve_repo_type: no-subscription
    - pve_root_password: qweasdzxc
  tasks:
    - name: One way to avoid apt_key once it is removed from your distro
      block:
              # - name: pve-enterprise |no apt key
              # ansible.builtin.get_url:
              # url: https://enterprise.proxmox.com/debian/key.asc
              # dest: /etc/apt/trusted.gpg.d/pve-enterprise.asc
        - name: pve-enterprise | apt source
          ansible.builtin.apt_repository:
            repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} InRelease"
            #repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/pve-enterprise.asc] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} {{ pve_repo_names[pve_repo_type] }}"
            state: present

    - name: Create new container with minimal options
      community.general.proxmox:
        vmid: 100
        node: uk-mc02
        api_user: root@pam
        api_password: 1q2w3e
        api_host: node1
        password: pve_root_password 
        hostname: example.odrg
        ostemplate: 'local:vztmpl/ubuntu-14.04-x86_64.tar.gz'
