---
- name: converge
  hosts: vault
  become: yes
  gather_facts: yes
  vars:
    vault_unseal_keys:
      - oEZk9MmbFS+c3Ewa/e9qoBulbLFyIjPLO0iHrTVETPCg
      - qWtUgAEuy+HAOxDpnj1noSmV0J8N+2I6LMWHCl+1+BeG
      - MtoaAGYrXKz1kPKtQUGQ9g6wb45jdcWAfTXGoekVyoNi
      - cv94tKmOc6hYgTwCd+X/cwyXR4Vl8QtktuBnNLgjhgR6
      - HguSYwAVBhRDrhPfD1ZejYebLJ71T3ISPK96rqVjYiCE
  roles:
    - role: robertdebock.vault
      vault_show_unseal_information: yes
      vault_store_root_token: yes
      vault_make_backup: no
