---
- name: prepare
  hosts: vault
  become: yes
  gather_facts: yes
  vars:
    vault_unseal_keys:
      - OsYsAhUpoxx2C0Z6k54S5PHRVxZOBmLNhBqgshMFqPOJ
      - a+h+Tn/bWWrM9IynbxSj40D/9b3m7d8kurEBNrOQt8gx
      - 0VKokdsFE8rbvBpj5HgswuE44dc93ZjTV+XqBcF5iLOq
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
      hashicorp_installation_method: manual
      hashicorp_products:
        - name: vault
          version: "1.11.2"
          type: oss
    - role: robertdebock.vault
      vault_show_unseal_information: yes
      vault_store_root_token: yes
      vault_make_backup: yes
      tags: vault
