---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    vault_unseal_keys:
      - gfKHmgQaiIpwH5Xw2oBBsfsvm4uxoh0uBjvJfR8ohSy1
      - ap/K9sVYMVj7/cN0dwUNrFGi+LROmIkbMKu2yXeeH+md
      - laFh3HZPMXrwQEoREhpD1QQkubkhEJdFX/wX/4n88hey
  roles:
    - role: robertdebock.vault
      vault_show_unseal_information: yes
      vault_store_root_token: yes
      vault_make_backup: yes
