---
- name: prepare
  hosts: vault
  become: yes
  gather_facts: yes
  vars:
    vault_unseal_keys:
      - x1HY+Y+7VeNhVR/I0Tx8r7bFVJrnzLiM3ImLALVjw8S8
      - 4K2M90rdSaQcRP4IvlsXiHTNXUAzQnlXTAjQk7EGRy
      - vbybU5B/50Z6U1S37T+LeTCdYLrUutpSAZP0Ze0QAcsT
      - dZMsSj5bG+ldIWyy2VtXRT/PQHKmLlawVqPWWNv5N1Rh
      - ydqNK5nQ+JnCaWq1qGOeMUQMoiVX3YEbWCDvbcDf+fie
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
      hashicorp_installation_method: manual
      hashicorp_products:
        - name: vault
          version: "1.11.2"
          type: oss
    - role: robertdebock.vault
      vault_show_unseal_information: yes
      vault_store_root_token: yes
      vault_make_backup: yes
      tags: vault
