---
- name: Set storage basepath for local
  set_fact:
    lxcostemplate_storage_path: /var/lib/vz/template/cache
  when: lxcostemplate_storage == "local"
- name: Set storage basepath for non-local
  set_fact:
    lxcostemplate_storage_path: "/mnt/pve/{{ lxcostemplate_storage }}/template/cache"
  when: lxcostemplate_storage != "local"

- include: prepare.yml
  delegate_to: "{{ pve_host }}"
- include: generate.yml
  delegate_to: "{{ pve_host }}"
  when:
    (not lxcostemplate_overwrite and not lxcostemplate_existing_image.stat.exists) or
    lxcostemplate_overwrite
