- name: Look for existing image
  stat:
    path: '{{ lxcostemplate_storage_path }}/{{ lxcostemplate_image }}.tar.gz'
  register: lxcostemplate_existing_image
  when: not lxcostemplate_overwrite

- block: # noqa unnamed-task
  - name: Get cluster VMs
    command: pvesh get /cluster/resources -type vm --output-format json
    register: cluster_vms
    changed_when: no
    check_mode: no
    become: yes
  - name: Get guest VMID
    set_fact:
      lxcostemplate_vmid: '{{ (cluster_vms.stdout | from_json | selectattr("name", "match", lxcostemplate_hostname) | map(attribute="vmid") | list).0 }}'
  when: not lxcostemplate_vmid
