- include_tasks: checks.yml

# This step is required to properly decrypt the root password
# if it is stored in ansible-vault
- name: Decrypt root password
  set_fact:
    pbs_root_password: "{{ pbs_root_password }}"
  no_log: true

- name: Root password is set
  user:
    name: root
    password: "{{ pbs_root_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"

- include_tasks: repo.yml

- include_tasks: smartd.yml
